directory: ~/music/beets
library: ~/music/beets/library.db
plugins: inline the info custom_album_tag

original_date: no
per_disc_numbering: yes
asciify_paths: no

import:
    move: no
    copy: yes
    timid: yes
    from_scratch: yes
    quiet_fallback: asis

kodi:
    host: localhost
    port: 8080
    user: kodi
    pwd: kodi

musicbrainz:
    searchlimit: 10

match:
    preferred:
        countries: ['DE', 'XE', 'XW', 'GB|U|UKK', 'US']
        media: ['Digital Media|File', 'CD']
        original_year: yes

paths:
    default: "%the{$albumartist}/\
              \
              $original_year - $album\
              %if{$multidisc,,%if{$disctitle, ($disctitle)}}\
              %aunique{}/\
              \
              %if{$multidisc,Disc $disc%if{$disctitle, ($disctitle)}/}\
              \
              $track $title"

    singleton: Non-Album/$artist/$title

    albumtype:soundtrack: Soundtracks/$album%aunique%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

    comp: Compilations/$album%aunique{}%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

# (1989, EMI, Parlophone, UK, CDP 7 92407 2)
aunique:
    keys: albumartist album
    disambiguators: release_year media label country catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

item_fields:
    multidisc: 1 if disctotal > 1 else 0

