directory: ~/music/beets
library: ~/music/beets/library.db
plugins: inline the info custom_album_tag kodiupdate

original_date: yes
per_disc_numbering: yes

import:
    move: yes
    timid: yes
    from_scratch: yes
    quiet_fallback: asis

kodi:
    host: localhost
    port: 8080
    user: kodi
    pwd: kodi

musicbrainz:
    searchlimit: 10

match:
    preferred:
        original_year: yes

paths:
    default: "%the{$albumartist}/\
              \
              $year - $album\
              %if{$multidisc,,%if{$disctitle, ($disctitle)}}\
              %if{$albumdisambig, ($albumdisambig)}\
              %aunique{}\
              %if{$multidisc,,$format_string}/\
              \
              %if{$multidisc,Disc $disc%if{$disctitle, ($disctitle)}$format_string/}\
              \
              $track - $title"

    singleton: Non-Album/$artist/$title

    albumtype:soundtrack: Soundtracks/$album%aunique%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

    comp: Compilations/$album%aunique{}%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

aunique:
    keys: albumartist album
    disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig media
    bracket: '[]'

item_fields:
    multidisc: 1 if disctotal > 1 else 0

