directory: ~/music/beets
library: ~/music/beets/library.db
plugins: inline the info fetchart embedart album_appendix

original_date: yes
per_disc_numbering: yes
asciify_paths: no
clutter: [Thumbs.DB, .DS_Store]

import:
    move: yes
    copy: no
    write: yes
    autotag: yes
    from_scratch: yes
    quiet_fallback: skip
    log: ~/music/beets/import.log

kodi:
    host: localhost
    port: 8080
    user: kodi
    pwd: kodi

musicbrainz:
    searchlimit: 10

match:
    strong_rec_thresh: 0.07
    preferred:
        countries: ['DE', 'XE', 'XW', 'GB|UK', 'US']
        media: ['Digital Media|File', 'CD']
        original_year: no
    ignored: missing_tracks unmatched_tracks
    ignore_video_tracks: no

paths:
    default: "%the{$albumartist}/\
              \
              $year - $album\
              %if{$multidisc,,%if{$disctitle, ($disctitle)}}\
              %aunique{}/\
              \
              %if{$multidisc,Disc $disc%if{$disctitle, ($disctitle)}/}\
              \
              $track $title"

    singleton: Non-Album/$artist/$title

    # albumtype:soundtrack: Soundtracks/$album%aunique{}%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

    comp: Compilations/$album%aunique{}%ifdef{source, [$source]}/%if{$multidisc,Disc $disc/}$track - $artist - $title

# (1989, EMI, Parlophone, UK, CDP 7 92407 2)
aunique:
    keys: albumartist album
    disambiguators: release_year media label country catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

item_fields:
    multidisc: 1 if disctotal > 1 else 0

